FROM ubuntu:latest
RUN apt-get update -y
RUN apt-get upgrade -y
RUN apt-get install -y curl git
RUN apt-get install -y gcc
RUN apt-get install -y clang-format
RUN apt-get install -y cmake
RUN apt-get install -y g++